spring.application.name: coupon-issuer-consumer
spring.profiles.active: local

spring.config.import:
  - classpath:app-config/infra-db.yml
  - classpath:app-config/infra-redis.yml
  - classpath:app-config/infra-kafka.yml

server.port: 8082
